// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: asciigame.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Frame is the top-level network message. On the wire each Frame is
// length-prefixed: a 4-byte big-endian uint32 length followed by that many
// bytes of the marshaled Frame. The payload oneof discriminates the message.
type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Frame_Login
	//	*Frame_Register
	//	*Frame_ListRooms
	//	*Frame_CreateRoom
	//	*Frame_JoinRoom
	//	*Frame_LeaveRoom
	//	*Frame_Ready
	//	*Frame_Move
	//	*Frame_Attack
	//	*Frame_UseItem
	//	*Frame_Chat
	//	*Frame_Logout
	//	*Frame_Ok
	//	*Frame_Error
	//	*Frame_RoomList
	//	*Frame_RoomInfo
	//	*Frame_PlayerJoin
	//	*Frame_PlayerLeave
	//	*Frame_GameStart
	//	*Frame_MapData
	//	*Frame_GameState
	//	*Frame_GameEvent
	//	*Frame_GameEnd
	//	*Frame_ChatMsg
	//	*Frame_Kick
	Payload       isFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_asciigame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetPayload() isFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetLogin() *Login {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Login); ok {
			return x.Login
		}
	}
	return nil
}

func (x *Frame) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *Frame) GetListRooms() *ListRooms {
	if x != nil {
		if x, ok := x.Payload.(*Frame_ListRooms); ok {
			return x.ListRooms
		}
	}
	return nil
}

func (x *Frame) GetCreateRoom() *CreateRoom {
	if x != nil {
		if x, ok := x.Payload.(*Frame_CreateRoom); ok {
			return x.CreateRoom
		}
	}
	return nil
}

func (x *Frame) GetJoinRoom() *JoinRoom {
	if x != nil {
		if x, ok := x.Payload.(*Frame_JoinRoom); ok {
			return x.JoinRoom
		}
	}
	return nil
}

func (x *Frame) GetLeaveRoom() *LeaveRoom {
	if x != nil {
		if x, ok := x.Payload.(*Frame_LeaveRoom); ok {
			return x.LeaveRoom
		}
	}
	return nil
}

func (x *Frame) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *Frame) GetMove() *Move {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *Frame) GetAttack() *Attack {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Attack); ok {
			return x.Attack
		}
	}
	return nil
}

func (x *Frame) GetUseItem() *UseItem {
	if x != nil {
		if x, ok := x.Payload.(*Frame_UseItem); ok {
			return x.UseItem
		}
	}
	return nil
}

func (x *Frame) GetChat() *Chat {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Frame) GetLogout() *Logout {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Logout); ok {
			return x.Logout
		}
	}
	return nil
}

func (x *Frame) GetOk() *Ok {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Ok); ok {
			return x.Ok
		}
	}
	return nil
}

func (x *Frame) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Frame) GetRoomList() *RoomList {
	if x != nil {
		if x, ok := x.Payload.(*Frame_RoomList); ok {
			return x.RoomList
		}
	}
	return nil
}

func (x *Frame) GetRoomInfo() *RoomInfo {
	if x != nil {
		if x, ok := x.Payload.(*Frame_RoomInfo); ok {
			return x.RoomInfo
		}
	}
	return nil
}

func (x *Frame) GetPlayerJoin() *PlayerJoin {
	if x != nil {
		if x, ok := x.Payload.(*Frame_PlayerJoin); ok {
			return x.PlayerJoin
		}
	}
	return nil
}

func (x *Frame) GetPlayerLeave() *PlayerLeave {
	if x != nil {
		if x, ok := x.Payload.(*Frame_PlayerLeave); ok {
			return x.PlayerLeave
		}
	}
	return nil
}

func (x *Frame) GetGameStart() *GameStart {
	if x != nil {
		if x, ok := x.Payload.(*Frame_GameStart); ok {
			return x.GameStart
		}
	}
	return nil
}

func (x *Frame) GetMapData() *MapData {
	if x != nil {
		if x, ok := x.Payload.(*Frame_MapData); ok {
			return x.MapData
		}
	}
	return nil
}

func (x *Frame) GetGameState() *GameState {
	if x != nil {
		if x, ok := x.Payload.(*Frame_GameState); ok {
			return x.GameState
		}
	}
	return nil
}

func (x *Frame) GetGameEvent() *GameEvent {
	if x != nil {
		if x, ok := x.Payload.(*Frame_GameEvent); ok {
			return x.GameEvent
		}
	}
	return nil
}

func (x *Frame) GetGameEnd() *GameEnd {
	if x != nil {
		if x, ok := x.Payload.(*Frame_GameEnd); ok {
			return x.GameEnd
		}
	}
	return nil
}

func (x *Frame) GetChatMsg() *ChatMsg {
	if x != nil {
		if x, ok := x.Payload.(*Frame_ChatMsg); ok {
			return x.ChatMsg
		}
	}
	return nil
}

func (x *Frame) GetKick() *Kick {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Kick); ok {
			return x.Kick
		}
	}
	return nil
}

type isFrame_Payload interface {
	isFrame_Payload()
}

type Frame_Login struct {
	// client -> server
	Login *Login `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type Frame_Register struct {
	Register *Register `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

type Frame_ListRooms struct {
	ListRooms *ListRooms `protobuf:"bytes,3,opt,name=list_rooms,json=listRooms,proto3,oneof"`
}

type Frame_CreateRoom struct {
	CreateRoom *CreateRoom `protobuf:"bytes,4,opt,name=create_room,json=createRoom,proto3,oneof"`
}

type Frame_JoinRoom struct {
	JoinRoom *JoinRoom `protobuf:"bytes,5,opt,name=join_room,json=joinRoom,proto3,oneof"`
}

type Frame_LeaveRoom struct {
	LeaveRoom *LeaveRoom `protobuf:"bytes,6,opt,name=leave_room,json=leaveRoom,proto3,oneof"`
}

type Frame_Ready struct {
	Ready *Ready `protobuf:"bytes,7,opt,name=ready,proto3,oneof"`
}

type Frame_Move struct {
	Move *Move `protobuf:"bytes,8,opt,name=move,proto3,oneof"`
}

type Frame_Attack struct {
	Attack *Attack `protobuf:"bytes,9,opt,name=attack,proto3,oneof"`
}

type Frame_UseItem struct {
	UseItem *UseItem `protobuf:"bytes,10,opt,name=use_item,json=useItem,proto3,oneof"`
}

type Frame_Chat struct {
	Chat *Chat `protobuf:"bytes,11,opt,name=chat,proto3,oneof"`
}

type Frame_Logout struct {
	Logout *Logout `protobuf:"bytes,12,opt,name=logout,proto3,oneof"`
}

type Frame_Ok struct {
	// server -> client
	Ok *Ok `protobuf:"bytes,13,opt,name=ok,proto3,oneof"`
}

type Frame_Error struct {
	Error *Error `protobuf:"bytes,14,opt,name=error,proto3,oneof"`
}

type Frame_RoomList struct {
	RoomList *RoomList `protobuf:"bytes,15,opt,name=room_list,json=roomList,proto3,oneof"`
}

type Frame_RoomInfo struct {
	RoomInfo *RoomInfo `protobuf:"bytes,16,opt,name=room_info,json=roomInfo,proto3,oneof"`
}

type Frame_PlayerJoin struct {
	PlayerJoin *PlayerJoin `protobuf:"bytes,17,opt,name=player_join,json=playerJoin,proto3,oneof"`
}

type Frame_PlayerLeave struct {
	PlayerLeave *PlayerLeave `protobuf:"bytes,18,opt,name=player_leave,json=playerLeave,proto3,oneof"`
}

type Frame_GameStart struct {
	GameStart *GameStart `protobuf:"bytes,19,opt,name=game_start,json=gameStart,proto3,oneof"`
}

type Frame_MapData struct {
	MapData *MapData `protobuf:"bytes,20,opt,name=map_data,json=mapData,proto3,oneof"`
}

type Frame_GameState struct {
	GameState *GameState `protobuf:"bytes,21,opt,name=game_state,json=gameState,proto3,oneof"`
}

type Frame_GameEvent struct {
	GameEvent *GameEvent `protobuf:"bytes,22,opt,name=game_event,json=gameEvent,proto3,oneof"`
}

type Frame_GameEnd struct {
	GameEnd *GameEnd `protobuf:"bytes,23,opt,name=game_end,json=gameEnd,proto3,oneof"`
}

type Frame_ChatMsg struct {
	ChatMsg *ChatMsg `protobuf:"bytes,24,opt,name=chat_msg,json=chatMsg,proto3,oneof"`
}

type Frame_Kick struct {
	Kick *Kick `protobuf:"bytes,25,opt,name=kick,proto3,oneof"`
}

func (*Frame_Login) isFrame_Payload() {}

func (*Frame_Register) isFrame_Payload() {}

func (*Frame_ListRooms) isFrame_Payload() {}

func (*Frame_CreateRoom) isFrame_Payload() {}

func (*Frame_JoinRoom) isFrame_Payload() {}

func (*Frame_LeaveRoom) isFrame_Payload() {}

func (*Frame_Ready) isFrame_Payload() {}

func (*Frame_Move) isFrame_Payload() {}

func (*Frame_Attack) isFrame_Payload() {}

func (*Frame_UseItem) isFrame_Payload() {}

func (*Frame_Chat) isFrame_Payload() {}

func (*Frame_Logout) isFrame_Payload() {}

func (*Frame_Ok) isFrame_Payload() {}

func (*Frame_Error) isFrame_Payload() {}

func (*Frame_RoomList) isFrame_Payload() {}

func (*Frame_RoomInfo) isFrame_Payload() {}

func (*Frame_PlayerJoin) isFrame_Payload() {}

func (*Frame_PlayerLeave) isFrame_Payload() {}

func (*Frame_GameStart) isFrame_Payload() {}

func (*Frame_MapData) isFrame_Payload() {}

func (*Frame_GameState) isFrame_Payload() {}

func (*Frame_GameEvent) isFrame_Payload() {}

func (*Frame_GameEnd) isFrame_Payload() {}

func (*Frame_ChatMsg) isFrame_Payload() {}

func (*Frame_Kick) isFrame_Payload() {}

type Login struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Login) Reset() {
	*x = Login{}
	mi := &file_asciigame_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{1}
}

func (x *Login) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Login) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_asciigame_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Register) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ListRooms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRooms) Reset() {
	*x = ListRooms{}
	mi := &file_asciigame_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRooms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRooms) ProtoMessage() {}

func (x *ListRooms) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRooms.ProtoReflect.Descriptor instead.
func (*ListRooms) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{3}
}

type CreateRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,2,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoom) Reset() {
	*x = CreateRoom{}
	mi := &file_asciigame_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoom) ProtoMessage() {}

func (x *CreateRoom) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoom.ProtoReflect.Descriptor instead.
func (*CreateRoom) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoom) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

type JoinRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoom) Reset() {
	*x = JoinRoom{}
	mi := &file_asciigame_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom) ProtoMessage() {}

func (x *JoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom.ProtoReflect.Descriptor instead.
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRoom) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type LeaveRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoom) Reset() {
	*x = LeaveRoom{}
	mi := &file_asciigame_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoom) ProtoMessage() {}

func (x *LeaveRoom) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoom.ProtoReflect.Descriptor instead.
func (*LeaveRoom) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{6}
}

type Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_asciigame_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{7}
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     string                 `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_asciigame_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{8}
}

func (x *Move) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type Attack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attack) Reset() {
	*x = Attack{}
	mi := &file_asciigame_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attack) ProtoMessage() {}

func (x *Attack) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attack.ProtoReflect.Descriptor instead.
func (*Attack) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{9}
}

type UseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItem) Reset() {
	*x = UseItem{}
	mi := &file_asciigame_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItem) ProtoMessage() {}

func (x *UseItem) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItem.ProtoReflect.Descriptor instead.
func (*UseItem) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{10}
}

func (x *UseItem) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_asciigame_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{11}
}

func (x *Chat) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Logout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logout) Reset() {
	*x = Logout{}
	mi := &file_asciigame_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logout) ProtoMessage() {}

func (x *Logout) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logout.ProtoReflect.Descriptor instead.
func (*Logout) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{12}
}

// Ok acknowledges a command. For a successful login, message is
// "Login successful" and player_id carries the assigned id (>0).
type Ok struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	PlayerId      int32                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ok) Reset() {
	*x = Ok{}
	mi := &file_asciigame_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ok) ProtoMessage() {}

func (x *Ok) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ok.ProtoReflect.Descriptor instead.
func (*Ok) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{13}
}

func (x *Ok) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Ok) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_asciigame_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{14}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RoomList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomInfo            `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomList) Reset() {
	*x = RoomList{}
	mi := &file_asciigame_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomList) ProtoMessage() {}

func (x *RoomList) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomList.ProtoReflect.Descriptor instead.
func (*RoomList) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{15}
}

func (x *RoomList) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PlayerCount   int32                  `protobuf:"varint,3,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,4,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` // 0=Waiting 1=Starting 2=Gaming 3=Ended
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_asciigame_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{16}
}

func (x *RoomInfo) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomInfo) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *RoomInfo) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *RoomInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type PlayerJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoin) Reset() {
	*x = PlayerJoin{}
	mi := &file_asciigame_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoin) ProtoMessage() {}

func (x *PlayerJoin) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoin.ProtoReflect.Descriptor instead.
func (*PlayerJoin) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{17}
}

func (x *PlayerJoin) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerJoin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type PlayerLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeave) Reset() {
	*x = PlayerLeave{}
	mi := &file_asciigame_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeave) ProtoMessage() {}

func (x *PlayerLeave) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeave.ProtoReflect.Descriptor instead.
func (*PlayerLeave) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{18}
}

func (x *PlayerLeave) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type GameStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStart) Reset() {
	*x = GameStart{}
	mi := &file_asciigame_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStart) ProtoMessage() {}

func (x *GameStart) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStart.ProtoReflect.Descriptor instead.
func (*GameStart) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{19}
}

type MapData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []string               `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapData) Reset() {
	*x = MapData{}
	mi := &file_asciigame_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapData) ProtoMessage() {}

func (x *MapData) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapData.ProtoReflect.Descriptor instead.
func (*MapData) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{20}
}

func (x *MapData) GetRows() []string {
	if x != nil {
		return x.Rows
	}
	return nil
}

type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Players       []*PlayerState         `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Items         []*ItemState           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	PoisonRadius  int32                  `protobuf:"varint,4,opt,name=poison_radius,json=poisonRadius,proto3" json:"poison_radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_asciigame_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{21}
}

func (x *GameState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GameState) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameState) GetItems() []*ItemState {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GameState) GetPoisonRadius() int32 {
	if x != nil {
		return x.PoisonRadius
	}
	return 0
}

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Hp            int32                  `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`
	Atk           int32                  `protobuf:"varint,5,opt,name=atk,proto3" json:"atk,omitempty"`
	Def           int32                  `protobuf:"varint,6,opt,name=def,proto3" json:"def,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"` // mirrors server PlayerStatus enum
	HasShield     bool                   `protobuf:"varint,8,opt,name=has_shield,json=hasShield,proto3" json:"has_shield,omitempty"`
	Inventory     []int32                `protobuf:"varint,9,rep,packed,name=inventory,proto3" json:"inventory,omitempty"` // up to 5 slots; 0 = empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_asciigame_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{22}
}

func (x *PlayerState) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerState) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerState) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerState) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *PlayerState) GetAtk() int32 {
	if x != nil {
		return x.Atk
	}
	return 0
}

func (x *PlayerState) GetDef() int32 {
	if x != nil {
		return x.Def
	}
	return 0
}

func (x *PlayerState) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PlayerState) GetHasShield() bool {
	if x != nil {
		return x.HasShield
	}
	return false
}

func (x *PlayerState) GetInventory() []int32 {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type ItemState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemState) Reset() {
	*x = ItemState{}
	mi := &file_asciigame_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemState) ProtoMessage() {}

func (x *ItemState) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemState.ProtoReflect.Descriptor instead.
func (*ItemState) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{23}
}

func (x *ItemState) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ItemState) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ItemState) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// GameEvent is a discrete combat/system event, separate from the periodic
// GameState broadcast. Its event oneof discriminates the kind.
type GameEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*GameEvent_Attack
	//	*GameEvent_Damage
	//	*GameEvent_Kill
	//	*GameEvent_Shield
	//	*GameEvent_AttackResult
	//	*GameEvent_Pickup
	//	*GameEvent_Poison
	//	*GameEvent_BuffWarning
	//	*GameEvent_BuffExpired
	Event         isGameEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_asciigame_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{24}
}

func (x *GameEvent) GetEvent() isGameEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *GameEvent) GetAttack() *AttackEvent {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_Attack); ok {
			return x.Attack
		}
	}
	return nil
}

func (x *GameEvent) GetDamage() *DamageEvent {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_Damage); ok {
			return x.Damage
		}
	}
	return nil
}

func (x *GameEvent) GetKill() *KillEvent {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_Kill); ok {
			return x.Kill
		}
	}
	return nil
}

func (x *GameEvent) GetShield() *ShieldEvent {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_Shield); ok {
			return x.Shield
		}
	}
	return nil
}

func (x *GameEvent) GetAttackResult() *AttackResultEvent {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_AttackResult); ok {
			return x.AttackResult
		}
	}
	return nil
}

func (x *GameEvent) GetPickup() *PickupEvent {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_Pickup); ok {
			return x.Pickup
		}
	}
	return nil
}

func (x *GameEvent) GetPoison() *PoisonEvent {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_Poison); ok {
			return x.Poison
		}
	}
	return nil
}

func (x *GameEvent) GetBuffWarning() *BuffWarningEvent {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_BuffWarning); ok {
			return x.BuffWarning
		}
	}
	return nil
}

func (x *GameEvent) GetBuffExpired() *BuffExpiredEvent {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_BuffExpired); ok {
			return x.BuffExpired
		}
	}
	return nil
}

type isGameEvent_Event interface {
	isGameEvent_Event()
}

type GameEvent_Attack struct {
	Attack *AttackEvent `protobuf:"bytes,1,opt,name=attack,proto3,oneof"`
}

type GameEvent_Damage struct {
	Damage *DamageEvent `protobuf:"bytes,2,opt,name=damage,proto3,oneof"`
}

type GameEvent_Kill struct {
	Kill *KillEvent `protobuf:"bytes,3,opt,name=kill,proto3,oneof"`
}

type GameEvent_Shield struct {
	Shield *ShieldEvent `protobuf:"bytes,4,opt,name=shield,proto3,oneof"`
}

type GameEvent_AttackResult struct {
	AttackResult *AttackResultEvent `protobuf:"bytes,5,opt,name=attack_result,json=attackResult,proto3,oneof"`
}

type GameEvent_Pickup struct {
	Pickup *PickupEvent `protobuf:"bytes,6,opt,name=pickup,proto3,oneof"`
}

type GameEvent_Poison struct {
	Poison *PoisonEvent `protobuf:"bytes,7,opt,name=poison,proto3,oneof"`
}

type GameEvent_BuffWarning struct {
	BuffWarning *BuffWarningEvent `protobuf:"bytes,8,opt,name=buff_warning,json=buffWarning,proto3,oneof"`
}

type GameEvent_BuffExpired struct {
	BuffExpired *BuffExpiredEvent `protobuf:"bytes,9,opt,name=buff_expired,json=buffExpired,proto3,oneof"`
}

func (*GameEvent_Attack) isGameEvent_Event() {}

func (*GameEvent_Damage) isGameEvent_Event() {}

func (*GameEvent_Kill) isGameEvent_Event() {}

func (*GameEvent_Shield) isGameEvent_Event() {}

func (*GameEvent_AttackResult) isGameEvent_Event() {}

func (*GameEvent_Pickup) isGameEvent_Event() {}

func (*GameEvent_Poison) isGameEvent_Event() {}

func (*GameEvent_BuffWarning) isGameEvent_Event() {}

func (*GameEvent_BuffExpired) isGameEvent_Event() {}

type AttackEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttackerId    int32                  `protobuf:"varint,1,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackEvent) Reset() {
	*x = AttackEvent{}
	mi := &file_asciigame_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackEvent) ProtoMessage() {}

func (x *AttackEvent) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackEvent.ProtoReflect.Descriptor instead.
func (*AttackEvent) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{25}
}

func (x *AttackEvent) GetAttackerId() int32 {
	if x != nil {
		return x.AttackerId
	}
	return 0
}

func (x *AttackEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AttackEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type DamageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttackerId    int32                  `protobuf:"varint,1,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`
	VictimId      int32                  `protobuf:"varint,2,opt,name=victim_id,json=victimId,proto3" json:"victim_id,omitempty"`
	Damage        int32                  `protobuf:"varint,3,opt,name=damage,proto3" json:"damage,omitempty"`
	Hp            int32                  `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DamageEvent) Reset() {
	*x = DamageEvent{}
	mi := &file_asciigame_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DamageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DamageEvent) ProtoMessage() {}

func (x *DamageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DamageEvent.ProtoReflect.Descriptor instead.
func (*DamageEvent) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{26}
}

func (x *DamageEvent) GetAttackerId() int32 {
	if x != nil {
		return x.AttackerId
	}
	return 0
}

func (x *DamageEvent) GetVictimId() int32 {
	if x != nil {
		return x.VictimId
	}
	return 0
}

func (x *DamageEvent) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *DamageEvent) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

type KillEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KillerId      int32                  `protobuf:"varint,1,opt,name=killer_id,json=killerId,proto3" json:"killer_id,omitempty"`
	VictimId      int32                  `protobuf:"varint,2,opt,name=victim_id,json=victimId,proto3" json:"victim_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillEvent) Reset() {
	*x = KillEvent{}
	mi := &file_asciigame_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillEvent) ProtoMessage() {}

func (x *KillEvent) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillEvent.ProtoReflect.Descriptor instead.
func (*KillEvent) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{27}
}

func (x *KillEvent) GetKillerId() int32 {
	if x != nil {
		return x.KillerId
	}
	return 0
}

func (x *KillEvent) GetVictimId() int32 {
	if x != nil {
		return x.VictimId
	}
	return 0
}

type ShieldEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttackerId    int32                  `protobuf:"varint,1,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`
	DefenderId    int32                  `protobuf:"varint,2,opt,name=defender_id,json=defenderId,proto3" json:"defender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShieldEvent) Reset() {
	*x = ShieldEvent{}
	mi := &file_asciigame_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShieldEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShieldEvent) ProtoMessage() {}

func (x *ShieldEvent) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShieldEvent.ProtoReflect.Descriptor instead.
func (*ShieldEvent) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{28}
}

func (x *ShieldEvent) GetAttackerId() int32 {
	if x != nil {
		return x.AttackerId
	}
	return 0
}

func (x *ShieldEvent) GetDefenderId() int32 {
	if x != nil {
		return x.DefenderId
	}
	return 0
}

type AttackResultEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttackerId    int32                  `protobuf:"varint,1,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`
	HitCount      int32                  `protobuf:"varint,2,opt,name=hit_count,json=hitCount,proto3" json:"hit_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackResultEvent) Reset() {
	*x = AttackResultEvent{}
	mi := &file_asciigame_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackResultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackResultEvent) ProtoMessage() {}

func (x *AttackResultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackResultEvent.ProtoReflect.Descriptor instead.
func (*AttackResultEvent) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{29}
}

func (x *AttackResultEvent) GetAttackerId() int32 {
	if x != nil {
		return x.AttackerId
	}
	return 0
}

func (x *AttackResultEvent) GetHitCount() int32 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

type PickupEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ItemType      int32                  `protobuf:"varint,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickupEvent) Reset() {
	*x = PickupEvent{}
	mi := &file_asciigame_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickupEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickupEvent) ProtoMessage() {}

func (x *PickupEvent) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickupEvent.ProtoReflect.Descriptor instead.
func (*PickupEvent) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{30}
}

func (x *PickupEvent) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PickupEvent) GetItemType() int32 {
	if x != nil {
		return x.ItemType
	}
	return 0
}

type PoisonEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoisonEvent) Reset() {
	*x = PoisonEvent{}
	mi := &file_asciigame_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoisonEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoisonEvent) ProtoMessage() {}

func (x *PoisonEvent) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoisonEvent.ProtoReflect.Descriptor instead.
func (*PoisonEvent) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{31}
}

type BuffWarningEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Seconds       int32                  `protobuf:"varint,2,opt,name=seconds,proto3" json:"seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuffWarningEvent) Reset() {
	*x = BuffWarningEvent{}
	mi := &file_asciigame_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuffWarningEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuffWarningEvent) ProtoMessage() {}

func (x *BuffWarningEvent) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuffWarningEvent.ProtoReflect.Descriptor instead.
func (*BuffWarningEvent) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{32}
}

func (x *BuffWarningEvent) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *BuffWarningEvent) GetSeconds() int32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

type BuffExpiredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuffExpiredEvent) Reset() {
	*x = BuffExpiredEvent{}
	mi := &file_asciigame_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuffExpiredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuffExpiredEvent) ProtoMessage() {}

func (x *BuffExpiredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuffExpiredEvent.ProtoReflect.Descriptor instead.
func (*BuffExpiredEvent) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{33}
}

func (x *BuffExpiredEvent) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type GameEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinnerId      int32                  `protobuf:"varint,1,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	Stats         string                 `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEnd) Reset() {
	*x = GameEnd{}
	mi := &file_asciigame_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEnd) ProtoMessage() {}

func (x *GameEnd) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEnd.ProtoReflect.Descriptor instead.
func (*GameEnd) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{34}
}

func (x *GameEnd) GetWinnerId() int32 {
	if x != nil {
		return x.WinnerId
	}
	return 0
}

func (x *GameEnd) GetStats() string {
	if x != nil {
		return x.Stats
	}
	return ""
}

type ChatMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMsg) Reset() {
	*x = ChatMsg{}
	mi := &file_asciigame_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg) ProtoMessage() {}

func (x *ChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{35}
}

func (x *ChatMsg) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Kick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kick) Reset() {
	*x = Kick{}
	mi := &file_asciigame_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kick) ProtoMessage() {}

func (x *Kick) ProtoReflect() protoreflect.Message {
	mi := &file_asciigame_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kick.ProtoReflect.Descriptor instead.
func (*Kick) Descriptor() ([]byte, []int) {
	return file_asciigame_proto_rawDescGZIP(), []int{36}
}

func (x *Kick) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_asciigame_proto protoreflect.FileDescriptor

const file_asciigame_proto_rawDesc = "" +
	"\n" +
	"\x0fasciigame.proto\x12\tasciigame\"\xd7\t\n" +
	"\x05Frame\x12(\n" +
	"\x05login\x18\x01 \x01(\v2\x10.asciigame.LoginH\x00R\x05login\x121\n" +
	"\bregister\x18\x02 \x01(\v2\x13.asciigame.RegisterH\x00R\bregister\x125\n" +
	"\n" +
	"list_rooms\x18\x03 \x01(\v2\x14.asciigame.ListRoomsH\x00R\tlistRooms\x128\n" +
	"\vcreate_room\x18\x04 \x01(\v2\x15.asciigame.CreateRoomH\x00R\n" +
	"createRoom\x122\n" +
	"\tjoin_room\x18\x05 \x01(\v2\x13.asciigame.JoinRoomH\x00R\bjoinRoom\x125\n" +
	"\n" +
	"leave_room\x18\x06 \x01(\v2\x14.asciigame.LeaveRoomH\x00R\tleaveRoom\x12(\n" +
	"\x05ready\x18\a \x01(\v2\x10.asciigame.ReadyH\x00R\x05ready\x12%\n" +
	"\x04move\x18\b \x01(\v2\x0f.asciigame.MoveH\x00R\x04move\x12+\n" +
	"\x06attack\x18\t \x01(\v2\x11.asciigame.AttackH\x00R\x06attack\x12/\n" +
	"\buse_item\x18\n" +
	" \x01(\v2\x12.asciigame.UseItemH\x00R\auseItem\x12%\n" +
	"\x04chat\x18\v \x01(\v2\x0f.asciigame.ChatH\x00R\x04chat\x12+\n" +
	"\x06logout\x18\f \x01(\v2\x11.asciigame.LogoutH\x00R\x06logout\x12\x1f\n" +
	"\x02ok\x18\r \x01(\v2\r.asciigame.OkH\x00R\x02ok\x12(\n" +
	"\x05error\x18\x0e \x01(\v2\x10.asciigame.ErrorH\x00R\x05error\x122\n" +
	"\troom_list\x18\x0f \x01(\v2\x13.asciigame.RoomListH\x00R\broomList\x122\n" +
	"\troom_info\x18\x10 \x01(\v2\x13.asciigame.RoomInfoH\x00R\broomInfo\x128\n" +
	"\vplayer_join\x18\x11 \x01(\v2\x15.asciigame.PlayerJoinH\x00R\n" +
	"playerJoin\x12;\n" +
	"\fplayer_leave\x18\x12 \x01(\v2\x16.asciigame.PlayerLeaveH\x00R\vplayerLeave\x125\n" +
	"\n" +
	"game_start\x18\x13 \x01(\v2\x14.asciigame.GameStartH\x00R\tgameStart\x12/\n" +
	"\bmap_data\x18\x14 \x01(\v2\x12.asciigame.MapDataH\x00R\amapData\x125\n" +
	"\n" +
	"game_state\x18\x15 \x01(\v2\x14.asciigame.GameStateH\x00R\tgameState\x125\n" +
	"\n" +
	"game_event\x18\x16 \x01(\v2\x14.asciigame.GameEventH\x00R\tgameEvent\x12/\n" +
	"\bgame_end\x18\x17 \x01(\v2\x12.asciigame.GameEndH\x00R\agameEnd\x12/\n" +
	"\bchat_msg\x18\x18 \x01(\v2\x12.asciigame.ChatMsgH\x00R\achatMsg\x12%\n" +
	"\x04kick\x18\x19 \x01(\v2\x0f.asciigame.KickH\x00R\x04kickB\t\n" +
	"\apayload\"?\n" +
	"\x05Login\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"B\n" +
	"\bRegister\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\v\n" +
	"\tListRooms\"A\n" +
	"\n" +
	"CreateRoom\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vmax_players\x18\x02 \x01(\x05R\n" +
	"maxPlayers\"#\n" +
	"\bJoinRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x05R\x06roomId\"\v\n" +
	"\tLeaveRoom\"\a\n" +
	"\x05Ready\"$\n" +
	"\x04Move\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\tR\tdirection\"\b\n" +
	"\x06Attack\"\x1f\n" +
	"\aUseItem\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\" \n" +
	"\x04Chat\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\b\n" +
	"\x06Logout\";\n" +
	"\x02Ok\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x05R\bplayerId\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\bRoomList\x12)\n" +
	"\x05rooms\x18\x01 \x03(\v2\x13.asciigame.RoomInfoR\x05rooms\"\x93\x01\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x05R\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fplayer_count\x18\x03 \x01(\x05R\vplayerCount\x12\x1f\n" +
	"\vmax_players\x18\x04 \x01(\x05R\n" +
	"maxPlayers\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"E\n" +
	"\n" +
	"PlayerJoin\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"*\n" +
	"\vPlayerLeave\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\"\v\n" +
	"\tGameStart\"\x1d\n" +
	"\aMapData\x12\x12\n" +
	"\x04rows\x18\x01 \x03(\tR\x04rows\"\xac\x01\n" +
	"\tGameState\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x120\n" +
	"\aplayers\x18\x02 \x03(\v2\x16.asciigame.PlayerStateR\aplayers\x12*\n" +
	"\x05items\x18\x03 \x03(\v2\x14.asciigame.ItemStateR\x05items\x12#\n" +
	"\rpoison_radius\x18\x04 \x01(\x05R\fpoisonRadius\"\xc2\x01\n" +
	"\vPlayerState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x0e\n" +
	"\x02hp\x18\x04 \x01(\x05R\x02hp\x12\x10\n" +
	"\x03atk\x18\x05 \x01(\x05R\x03atk\x12\x10\n" +
	"\x03def\x18\x06 \x01(\x05R\x03def\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"has_shield\x18\b \x01(\bR\thasShield\x12\x1c\n" +
	"\tinventory\x18\t \x03(\x05R\tinventory\";\n" +
	"\tItemState\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\"\x83\x04\n" +
	"\tGameEvent\x120\n" +
	"\x06attack\x18\x01 \x01(\v2\x16.asciigame.AttackEventH\x00R\x06attack\x120\n" +
	"\x06damage\x18\x02 \x01(\v2\x16.asciigame.DamageEventH\x00R\x06damage\x12*\n" +
	"\x04kill\x18\x03 \x01(\v2\x14.asciigame.KillEventH\x00R\x04kill\x120\n" +
	"\x06shield\x18\x04 \x01(\v2\x16.asciigame.ShieldEventH\x00R\x06shield\x12C\n" +
	"\rattack_result\x18\x05 \x01(\v2\x1c.asciigame.AttackResultEventH\x00R\fattackResult\x120\n" +
	"\x06pickup\x18\x06 \x01(\v2\x16.asciigame.PickupEventH\x00R\x06pickup\x120\n" +
	"\x06poison\x18\a \x01(\v2\x16.asciigame.PoisonEventH\x00R\x06poison\x12@\n" +
	"\fbuff_warning\x18\b \x01(\v2\x1b.asciigame.BuffWarningEventH\x00R\vbuffWarning\x12@\n" +
	"\fbuff_expired\x18\t \x01(\v2\x1b.asciigame.BuffExpiredEventH\x00R\vbuffExpiredB\a\n" +
	"\x05event\"J\n" +
	"\vAttackEvent\x12\x1f\n" +
	"\vattacker_id\x18\x01 \x01(\x05R\n" +
	"attackerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"s\n" +
	"\vDamageEvent\x12\x1f\n" +
	"\vattacker_id\x18\x01 \x01(\x05R\n" +
	"attackerId\x12\x1b\n" +
	"\tvictim_id\x18\x02 \x01(\x05R\bvictimId\x12\x16\n" +
	"\x06damage\x18\x03 \x01(\x05R\x06damage\x12\x0e\n" +
	"\x02hp\x18\x04 \x01(\x05R\x02hp\"E\n" +
	"\tKillEvent\x12\x1b\n" +
	"\tkiller_id\x18\x01 \x01(\x05R\bkillerId\x12\x1b\n" +
	"\tvictim_id\x18\x02 \x01(\x05R\bvictimId\"O\n" +
	"\vShieldEvent\x12\x1f\n" +
	"\vattacker_id\x18\x01 \x01(\x05R\n" +
	"attackerId\x12\x1f\n" +
	"\vdefender_id\x18\x02 \x01(\x05R\n" +
	"defenderId\"Q\n" +
	"\x11AttackResultEvent\x12\x1f\n" +
	"\vattacker_id\x18\x01 \x01(\x05R\n" +
	"attackerId\x12\x1b\n" +
	"\thit_count\x18\x02 \x01(\x05R\bhitCount\"G\n" +
	"\vPickupEvent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\x12\x1b\n" +
	"\titem_type\x18\x02 \x01(\x05R\bitemType\"\r\n" +
	"\vPoisonEvent\"I\n" +
	"\x10BuffWarningEvent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\x12\x18\n" +
	"\aseconds\x18\x02 \x01(\x05R\aseconds\"/\n" +
	"\x10BuffExpiredEvent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\"<\n" +
	"\aGameEnd\x12\x1b\n" +
	"\twinner_id\x18\x01 \x01(\x05R\bwinnerId\x12\x14\n" +
	"\x05stats\x18\x02 \x01(\tR\x05stats\";\n" +
	"\aChatMsg\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1e\n" +
	"\x04Kick\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reasonB=Z;github.com/heartlazyli/asciigame/internal/protocol;protocolb\x06proto3"

var (
	file_asciigame_proto_rawDescOnce sync.Once
	file_asciigame_proto_rawDescData []byte
)

func file_asciigame_proto_rawDescGZIP() []byte {
	file_asciigame_proto_rawDescOnce.Do(func() {
		file_asciigame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asciigame_proto_rawDesc), len(file_asciigame_proto_rawDesc)))
	})
	return file_asciigame_proto_rawDescData
}

var file_asciigame_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_asciigame_proto_goTypes = []any{
	(*Frame)(nil),             // 0: asciigame.Frame
	(*Login)(nil),             // 1: asciigame.Login
	(*Register)(nil),          // 2: asciigame.Register
	(*ListRooms)(nil),         // 3: asciigame.ListRooms
	(*CreateRoom)(nil),        // 4: asciigame.CreateRoom
	(*JoinRoom)(nil),          // 5: asciigame.JoinRoom
	(*LeaveRoom)(nil),         // 6: asciigame.LeaveRoom
	(*Ready)(nil),             // 7: asciigame.Ready
	(*Move)(nil),              // 8: asciigame.Move
	(*Attack)(nil),            // 9: asciigame.Attack
	(*UseItem)(nil),           // 10: asciigame.UseItem
	(*Chat)(nil),              // 11: asciigame.Chat
	(*Logout)(nil),            // 12: asciigame.Logout
	(*Ok)(nil),                // 13: asciigame.Ok
	(*Error)(nil),             // 14: asciigame.Error
	(*RoomList)(nil),          // 15: asciigame.RoomList
	(*RoomInfo)(nil),          // 16: asciigame.RoomInfo
	(*PlayerJoin)(nil),        // 17: asciigame.PlayerJoin
	(*PlayerLeave)(nil),       // 18: asciigame.PlayerLeave
	(*GameStart)(nil),         // 19: asciigame.GameStart
	(*MapData)(nil),           // 20: asciigame.MapData
	(*GameState)(nil),         // 21: asciigame.GameState
	(*PlayerState)(nil),       // 22: asciigame.PlayerState
	(*ItemState)(nil),         // 23: asciigame.ItemState
	(*GameEvent)(nil),         // 24: asciigame.GameEvent
	(*AttackEvent)(nil),       // 25: asciigame.AttackEvent
	(*DamageEvent)(nil),       // 26: asciigame.DamageEvent
	(*KillEvent)(nil),         // 27: asciigame.KillEvent
	(*ShieldEvent)(nil),       // 28: asciigame.ShieldEvent
	(*AttackResultEvent)(nil), // 29: asciigame.AttackResultEvent
	(*PickupEvent)(nil),       // 30: asciigame.PickupEvent
	(*PoisonEvent)(nil),       // 31: asciigame.PoisonEvent
	(*BuffWarningEvent)(nil),  // 32: asciigame.BuffWarningEvent
	(*BuffExpiredEvent)(nil),  // 33: asciigame.BuffExpiredEvent
	(*GameEnd)(nil),           // 34: asciigame.GameEnd
	(*ChatMsg)(nil),           // 35: asciigame.ChatMsg
	(*Kick)(nil),              // 36: asciigame.Kick
}
var file_asciigame_proto_depIdxs = []int32{
	1,  // 0: asciigame.Frame.login:type_name -> asciigame.Login
	2,  // 1: asciigame.Frame.register:type_name -> asciigame.Register
	3,  // 2: asciigame.Frame.list_rooms:type_name -> asciigame.ListRooms
	4,  // 3: asciigame.Frame.create_room:type_name -> asciigame.CreateRoom
	5,  // 4: asciigame.Frame.join_room:type_name -> asciigame.JoinRoom
	6,  // 5: asciigame.Frame.leave_room:type_name -> asciigame.LeaveRoom
	7,  // 6: asciigame.Frame.ready:type_name -> asciigame.Ready
	8,  // 7: asciigame.Frame.move:type_name -> asciigame.Move
	9,  // 8: asciigame.Frame.attack:type_name -> asciigame.Attack
	10, // 9: asciigame.Frame.use_item:type_name -> asciigame.UseItem
	11, // 10: asciigame.Frame.chat:type_name -> asciigame.Chat
	12, // 11: asciigame.Frame.logout:type_name -> asciigame.Logout
	13, // 12: asciigame.Frame.ok:type_name -> asciigame.Ok
	14, // 13: asciigame.Frame.error:type_name -> asciigame.Error
	15, // 14: asciigame.Frame.room_list:type_name -> asciigame.RoomList
	16, // 15: asciigame.Frame.room_info:type_name -> asciigame.RoomInfo
	17, // 16: asciigame.Frame.player_join:type_name -> asciigame.PlayerJoin
	18, // 17: asciigame.Frame.player_leave:type_name -> asciigame.PlayerLeave
	19, // 18: asciigame.Frame.game_start:type_name -> asciigame.GameStart
	20, // 19: asciigame.Frame.map_data:type_name -> asciigame.MapData
	21, // 20: asciigame.Frame.game_state:type_name -> asciigame.GameState
	24, // 21: asciigame.Frame.game_event:type_name -> asciigame.GameEvent
	34, // 22: asciigame.Frame.game_end:type_name -> asciigame.GameEnd
	35, // 23: asciigame.Frame.chat_msg:type_name -> asciigame.ChatMsg
	36, // 24: asciigame.Frame.kick:type_name -> asciigame.Kick
	16, // 25: asciigame.RoomList.rooms:type_name -> asciigame.RoomInfo
	22, // 26: asciigame.GameState.players:type_name -> asciigame.PlayerState
	23, // 27: asciigame.GameState.items:type_name -> asciigame.ItemState
	25, // 28: asciigame.GameEvent.attack:type_name -> asciigame.AttackEvent
	26, // 29: asciigame.GameEvent.damage:type_name -> asciigame.DamageEvent
	27, // 30: asciigame.GameEvent.kill:type_name -> asciigame.KillEvent
	28, // 31: asciigame.GameEvent.shield:type_name -> asciigame.ShieldEvent
	29, // 32: asciigame.GameEvent.attack_result:type_name -> asciigame.AttackResultEvent
	30, // 33: asciigame.GameEvent.pickup:type_name -> asciigame.PickupEvent
	31, // 34: asciigame.GameEvent.poison:type_name -> asciigame.PoisonEvent
	32, // 35: asciigame.GameEvent.buff_warning:type_name -> asciigame.BuffWarningEvent
	33, // 36: asciigame.GameEvent.buff_expired:type_name -> asciigame.BuffExpiredEvent
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_asciigame_proto_init() }
func file_asciigame_proto_init() {
	if File_asciigame_proto != nil {
		return
	}
	file_asciigame_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Login)(nil),
		(*Frame_Register)(nil),
		(*Frame_ListRooms)(nil),
		(*Frame_CreateRoom)(nil),
		(*Frame_JoinRoom)(nil),
		(*Frame_LeaveRoom)(nil),
		(*Frame_Ready)(nil),
		(*Frame_Move)(nil),
		(*Frame_Attack)(nil),
		(*Frame_UseItem)(nil),
		(*Frame_Chat)(nil),
		(*Frame_Logout)(nil),
		(*Frame_Ok)(nil),
		(*Frame_Error)(nil),
		(*Frame_RoomList)(nil),
		(*Frame_RoomInfo)(nil),
		(*Frame_PlayerJoin)(nil),
		(*Frame_PlayerLeave)(nil),
		(*Frame_GameStart)(nil),
		(*Frame_MapData)(nil),
		(*Frame_GameState)(nil),
		(*Frame_GameEvent)(nil),
		(*Frame_GameEnd)(nil),
		(*Frame_ChatMsg)(nil),
		(*Frame_Kick)(nil),
	}
	file_asciigame_proto_msgTypes[24].OneofWrappers = []any{
		(*GameEvent_Attack)(nil),
		(*GameEvent_Damage)(nil),
		(*GameEvent_Kill)(nil),
		(*GameEvent_Shield)(nil),
		(*GameEvent_AttackResult)(nil),
		(*GameEvent_Pickup)(nil),
		(*GameEvent_Poison)(nil),
		(*GameEvent_BuffWarning)(nil),
		(*GameEvent_BuffExpired)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asciigame_proto_rawDesc), len(file_asciigame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_asciigame_proto_goTypes,
		DependencyIndexes: file_asciigame_proto_depIdxs,
		MessageInfos:      file_asciigame_proto_msgTypes,
	}.Build()
	File_asciigame_proto = out.File
	file_asciigame_proto_goTypes = nil
	file_asciigame_proto_depIdxs = nil
}
